// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/codex/login": {
            "post": {
                "description": "Runs ` + "`" + `codex login --device-auth` + "`" + ` and streams log lines as SSE events.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "codex"
                ],
                "summary": "Trigger Codex device login",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/codex/status": {
            "get": {
                "description": "Returns Codex CLI version, login status, and installed plugin list.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "codex"
                ],
                "summary": "Codex CLI status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/github/ingest": {
            "post": {
                "description": "Fetches a GitHub issue, PR, or commit by URI and returns a provenance-rich event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "github"
                ],
                "summary": "Ingest a GitHub artifact",
                "parameters": [
                    {
                        "description": "GitHub ingest request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GithubIngest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GithubIngest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/github/ingest/stream": {
            "post": {
                "description": "Streams Codex CLI progress via SSE, then emits a result event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "github"
                ],
                "summary": "Stream GitHub Codex ingest",
                "parameters": [
                    {
                        "description": "GitHub ingest request (provider must be codex)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GithubIngest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/github/status": {
            "get": {
                "description": "Returns token availability, source (env/none), and the authenticated GitHub login.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "github"
                ],
                "summary": "GitHub connection status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns ok when the API process is running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slack/callback": {
            "get": {
                "description": "Receives the OAuth code from Slack, exchanges it for a token, and stores it locally.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "Slack OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from Slack",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF state token",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML confirmation page",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slack/connect": {
            "get": {
                "description": "Generates a CSRF state token and redirects to Slack's OAuth consent page.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "Initiate Slack OAuth",
                "responses": {
                    "302": {
                        "description": "Redirect to Slack OAuth",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slack/ingest": {
            "post": {
                "description": "Fetches messages from a Slack channel by URI and returns a provenance-rich event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "Ingest a Slack channel or message",
                "parameters": [
                    {
                        "description": "Slack ingest request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SlackIngest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SlackIngest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slack/ingest/stream": {
            "post": {
                "description": "Streams Codex CLI progress via SSE, then emits a result event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "Stream Slack Codex ingest",
                "parameters": [
                    {
                        "description": "Slack ingest request (provider must be codex)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SlackIngest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/slack/status": {
            "get": {
                "description": "Returns token availability, source (env/oauth/none), workspace name, and OAuth readiness.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "Slack connection status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "events.Event": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "occurred_at": {
                    "type": "string"
                },
                "schema_version": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "trace_id": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/events.Type"
                }
            }
        },
        "events.Type": {
            "type": "string",
            "enum": [
                "document.ingested",
                "document.normalized",
                "entity.extracted",
                "identity.resolved",
                "relationship.created",
                "mismatch.detected",
                "codex.analysis.completed"
            ],
            "x-enum-varnames": [
                "DocumentIngested",
                "DocumentNormalized",
                "EntityExtracted",
                "IdentityResolved",
                "RelationshipCreated",
                "MismatchDetected",
                "CodexAnalysisComplete"
            ]
        },
        "request.GithubIngest": {
            "type": "object",
            "properties": {
                "provider": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "request.SlackIngest": {
            "type": "object",
            "properties": {
                "provider": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "response.GithubIngest": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "connector": {
                    "type": "string"
                },
                "event": {
                    "$ref": "#/definitions/events.Event"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "preview": {
                    "type": "string"
                }
            }
        },
        "response.SlackIngest": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "connector": {
                    "type": "string"
                },
                "event": {
                    "$ref": "#/definitions/events.Event"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "preview": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ContextOS API",
	Description:      "Local-first pipeline API for ingesting and reasoning over engineering context.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
